AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Helping customers break down data silos with AWS Integration services (SO9096)

##  To use this template, you must have installed the below extractors and created their service as per pre-requisites.  Once you have, simply find and replace the service details for each 
##  By default this schedules the below flows to run every five minutes
##  2LIS_12_VCITM  - /sap/opu/odata/sap/ZDELIVERIES_SRV/EntityOf2LIS_12_VCITM
##  2LIS_12_VCHDR  - /sap/opu/odata/sap/ZDELIVERIES_SRV/EntityOf2LIS_12_VCHDR
##  2LIS_11_VAITM  - /sap/opu/odata/sap/ZSALES_ORDERS_SRV/EntityOf2LIS_11_VAITM 
##  2LIS_11_VAHDR  - /sap/opu/odata/sap/ZSALES_ORDERS_SRV/EntityOf2LIS_11_VAHDR 
##  2LIS_13_VDITM  - /sap/opu/odata/sap/ZINVOICES_SRV/EntityOf2LIS_13_VDITM
##  2LIS_13_VDHDR  - /sap/opu/odata/sap/ZINVOICES_SRV/EntityOf2LIS_13_VDHDR

Parameters:
  ConnectorName:
    Description: The name of the SAP source system connection
    Type: String

  AppFlowSAPStartTime: 
    Description: EPOC date of first run for flow
    Type: Number

  DestinationS3BucketName: 
    Description: Name of the Destination S3 Bucket
    Type: String


Resources:        
  # Create Amazon AppFlow to pull data from SAP and store into S3.  Seperate resource name for each extractor connection (ie. for each flow)
  cf2LIS12VCITMtoS3:
    Type: AWS::AppFlow::Flow
    Properties: 
      FlowName: cf_2lis_12_vcitm
      FlowStatus: Active      
      Description: 'Pull data from SAP and saves into S3 for 2LIS_12_VCITM Delivery Item'
      TriggerConfig:
          TriggerType: Scheduled
          TriggerProperties:
            DataPullMode: Incremental
            ## If you wish to extract the transaction data at a different frequency, update here
            ScheduleExpression: rate(5minutes)         
            ScheduleStartTime: !Ref AppFlowSAPStartTime
      SourceFlowConfig:
        ConnectorProfileName: !Ref ConnectorName
        ConnectorType: SAPOData
        SourceConnectorProperties:
          SAPOData:
            #  Change this to your ObjectPath
            ObjectPath: /sap/opu/odata/sap/ZDELIVERIES_SRV/EntityOf2LIS_12_VCITM  
      DestinationFlowConfigList:
       - ConnectorType: S3
         DestinationConnectorProperties:
          S3:
            BucketName: !Ref DestinationS3BucketName
            S3OutputFormatConfig:
               FileType: JSON
               AggregationConfig:
                aggregationType: None
               PrefixConfig: 
                  PrefixFormat: HOUR
                  PrefixType: PATH_AND_FILENAME        
      Tasks:
      - TaskType: Map_all
        SourceFields: []
        TaskProperties:
        - Key: EXCLUDE_SOURCE_FIELDS_LIST
          Value: '[]'
        ConnectorOperator:
          SAPOData: NO_OP

  # Create Amazon AppFlow to pull data from SAP and store into S3.  Seperate resource name for each extractor connection (ie. for each flow)
  cf2LIS12VCHDRtoS3:
    Type: AWS::AppFlow::Flow
    Properties: 
      FlowName: cf_2lis_12_vchdr
      FlowStatus: Active      
      Description: 'Pull data from SAP and saves into S3 for 2LIS_12_VCHDR Delivery Header'
      TriggerConfig:
          TriggerType: Scheduled
          TriggerProperties:
            DataPullMode: Incremental
            ## If you wish to extract the transaction data at a different frequency, update here
            ScheduleExpression: rate(5minutes)         
            ScheduleStartTime: !Ref AppFlowSAPStartTime
      SourceFlowConfig:
        ConnectorProfileName: !Ref ConnectorName
        ConnectorType: SAPOData
        SourceConnectorProperties:
          SAPOData:
            #  Change this to your ObjectPath
            ObjectPath: /sap/opu/odata/sap/ZDELIVERIES_SRV/EntityOf2LIS_12_VCHDR  
      DestinationFlowConfigList:
       - ConnectorType: S3
         DestinationConnectorProperties:
          S3:
            BucketName: !Ref DestinationS3BucketName
            S3OutputFormatConfig:
               FileType: JSON
               AggregationConfig:
                aggregationType: None
               PrefixConfig: 
                  PrefixFormat: HOUR
                  PrefixType: PATH_AND_FILENAME        
      Tasks:
      - TaskType: Map_all
        SourceFields: []
        TaskProperties:
        - Key: EXCLUDE_SOURCE_FIELDS_LIST
          Value: '[]'
        ConnectorOperator:
          SAPOData: NO_OP

  # Create Amazon AppFlow to pull data from SAP and store into S3.  Seperate resource name for each extractor connection (ie. for each flow)
  cf2LIS11VAHDRtoS3:
    Type: AWS::AppFlow::Flow
    Properties: 
      FlowName: cf_2lis_11_vahdr
      FlowStatus: Active      
      Description: 'Pull data from SAP and saves into S3 for 2LIS_11_VAHDR Sales Order Header'
      TriggerConfig:
          TriggerType: Scheduled
          TriggerProperties:
            DataPullMode: Incremental
            ## If you wish to extract the transaction data at a different frequency, update here
            ScheduleExpression: rate(5minutes)         
            ScheduleStartTime: !Ref AppFlowSAPStartTime
      SourceFlowConfig:
        ConnectorProfileName: !Ref ConnectorName
        ConnectorType: SAPOData
        SourceConnectorProperties:
          SAPOData:
            #  Change this to your ObjectPath
            ObjectPath: /sap/opu/odata/sap/ZSALES_ORDERS_SRV/EntityOf2LIS_11_VAHDR  
      DestinationFlowConfigList:
       - ConnectorType: S3
         DestinationConnectorProperties:
          S3:
            BucketName: !Ref DestinationS3BucketName
            S3OutputFormatConfig:
               FileType: JSON
               AggregationConfig:
                aggregationType: None
               PrefixConfig: 
                  PrefixFormat: HOUR
                  PrefixType: PATH_AND_FILENAME        
      Tasks:
      - TaskType: Map_all
        SourceFields: []
        TaskProperties:
        - Key: EXCLUDE_SOURCE_FIELDS_LIST
          Value: '[]'
        ConnectorOperator:
          SAPOData: NO_OP 

  # Create Amazon AppFlow to pull data from SAP and store into S3.  Seperate resource name for each extractor connection (ie. for each flow)
  cf2LIS11VAITMtoS3:
    Type: AWS::AppFlow::Flow
    Properties: 
      FlowName: cf_2lis_11_vaitm
      FlowStatus: Active      
      Description: 'Pull data from SAP and saves into S3 for 2LIS_11_VAITM Sales Order Item'
      TriggerConfig:
          TriggerType: Scheduled
          TriggerProperties:
            DataPullMode: Incremental
            ## If you wish to extract the transaction data at a different frequency, update here
            ScheduleExpression: rate(5minutes)         
            ScheduleStartTime: !Ref AppFlowSAPStartTime
      SourceFlowConfig:
        ConnectorProfileName: !Ref ConnectorName
        ConnectorType: SAPOData
        SourceConnectorProperties:
          SAPOData:
            #  Change this to your ObjectPath
            ObjectPath: /sap/opu/odata/sap/ZSALES_ORDERS_SRV/EntityOf2LIS_11_VAITM  
      DestinationFlowConfigList:
       - ConnectorType: S3
         DestinationConnectorProperties:
          S3:
            BucketName: !Ref DestinationS3BucketName
            S3OutputFormatConfig:
               FileType: JSON
               AggregationConfig:
                aggregationType: None
               PrefixConfig: 
                  PrefixFormat: HOUR
                  PrefixType: PATH_AND_FILENAME        
      Tasks:
      - TaskType: Map_all
        SourceFields: []
        TaskProperties:
        - Key: EXCLUDE_SOURCE_FIELDS_LIST
          Value: '[]'
        ConnectorOperator:
          SAPOData: NO_OP        
  
  # Create Amazon AppFlow to pull data from SAP and store into S3.  Seperate resource name for each extractor connection (ie. for each flow)
  cf2LIS13VDITMtoS3:
    Type: AWS::AppFlow::Flow
    Properties: 
      FlowName: cf_2lis_13_vditm
      FlowStatus: Active      
      Description: 'Pull data from SAP and saves into S3 for 2LIS_13_VDITM Invoice Item'
      TriggerConfig:
          TriggerType: Scheduled
          TriggerProperties:
            DataPullMode: Incremental
            ## If you wish to extract the transaction data at a different frequency, update here
            ScheduleExpression: rate(5minutes)         
            ScheduleStartTime: !Ref AppFlowSAPStartTime
      SourceFlowConfig:
        ConnectorProfileName: !Ref ConnectorName
        ConnectorType: SAPOData
        SourceConnectorProperties:
          SAPOData:
            #  Change this to your ObjectPath
            ObjectPath: /sap/opu/odata/sap/ZINVOICES_SRV/EntityOf2LIS_13_VDITM  
      DestinationFlowConfigList:
       - ConnectorType: S3
         DestinationConnectorProperties:
          S3:
            BucketName: !Ref DestinationS3BucketName
            S3OutputFormatConfig:
               FileType: JSON
               AggregationConfig:
                aggregationType: None
               PrefixConfig: 
                  PrefixFormat: HOUR
                  PrefixType: PATH_AND_FILENAME        
      Tasks:
      - TaskType: Map_all
        SourceFields: []
        TaskProperties:
        - Key: EXCLUDE_SOURCE_FIELDS_LIST
          Value: '[]'
        ConnectorOperator:
          SAPOData: NO_OP

  # Create Amazon AppFlow to pull data from SAP and store into S3.  Seperate resource name for each extractor connection (ie. for each flow)
  cf2LIS13VDHDRtoS3:
    Type: AWS::AppFlow::Flow
    Properties: 
      FlowName: cf_2lis_13_vdhdr
      FlowStatus: Active      
      Description: 'Pull data from SAP and saves into S3 for 2LIS_13_VDHDR Invoice Header'
      TriggerConfig:
          TriggerType: Scheduled
          TriggerProperties:
            DataPullMode: Incremental
            ## If you wish to extract the transaction data at a different frequency, update here
            ScheduleExpression: rate(5minutes)         
            ScheduleStartTime: !Ref AppFlowSAPStartTime
      SourceFlowConfig:
        ConnectorProfileName: !Ref ConnectorName
        ConnectorType: SAPOData
        SourceConnectorProperties:
          SAPOData:
            #  Change this to your ObjectPath
            ObjectPath: /sap/opu/odata/sap/ZINVOICES_SRV/EntityOf2LIS_13_VDHDR  
      DestinationFlowConfigList:
       - ConnectorType: S3
         DestinationConnectorProperties:
          S3:
            BucketName: !Ref DestinationS3BucketName
            S3OutputFormatConfig:
               FileType: JSON
               AggregationConfig:
                aggregationType: None
               PrefixConfig: 
                  PrefixFormat: HOUR
                  PrefixType: PATH_AND_FILENAME        
      Tasks:
      - TaskType: Map_all
        SourceFields: []
        TaskProperties:
        - Key: EXCLUDE_SOURCE_FIELDS_LIST
          Value: '[]'
        ConnectorOperator:
          SAPOData: NO_OP                                    